version: "3.3"
services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - flaresolverr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: on-failure
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info